### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by liammulh** [ClinGen/stanford-affils#1]
## :white_check_mark: Scaffold basic CRUD application (~1 month)
- Used built in Django CRUD.

Follow https://hypermedia.systems as a guide.

## Add user authentication (~1 week)
- Used built in Django user authentication.
- [x] Schedule meeting with Matt about login.
- [x] #40
- [boto3 Credentials](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html)
- [boto3 CognitoIdentityProvider](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-idp.html)
- [boto3 initiate_auth](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-idp/client/initiate_auth.html#initiate-auth)
- [boto3 get_user](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-idp/client/get_user.html)

## :white_check_mark: Add JSON data API for other applications to CRUD affiliations (~1 week without the OpenAPI)

- [Guide to creating a good JSON data API](https://hypermedia.systems/json-data-apis/)

## Deploy test instance to on-prem server (~1 week)

- See [*DevOps for the Desperate: A Hands-On Survival Guide*](https://nostarch.com/devops-desperate). (Ask me about this.)
- [x] Create plan for configuring server using Ansible
- [x] Create plan for deploying to the server via Ansible

## Deploy production instance to AWS (~2 weeks)

- [x] Talk to Ryan about using Lightsail
- [Use Lightsail Ubuntu VPS?](https://aws.amazon.com/lightsail/)
- [x] Create plan for configuring server via Ansible
- [x] Create plan for deploying to the server via Ansible

## Conform to Gecko best practices (~1 week)

See the best practices spreadsheet [here](https://docs.google.com/spreadsheets/d/1MLeEQE-v3eEnEtKNG4oJ8q6a8pal9q462TTgVcodcg4/edit?pli=1#gid=0).

- [x] #3
- [x] #10
- [x] #12
- [x] #16
- [x] #18
- [x] Write UI tests for important bits of UI
  - Since we're not using a front end framework, we're just testing that certain important bits of HTML are in the response.
- [x] #23
- [x] #28
- [x] #31
- [x] Check this checkbox once you have IaC set up
- [x] Set up AWS monitoring
- [x] Set up AWS backups
- [x] Create system for managing secrets
- ~~[ ] Collect metrics~~
- [x] #19
- [x] #20
- [x] #21

## Set up documentation system

- [x] #14
- [x] #17

## Use production data (~1 week)

- [x] Discuss using correct status for affiliations

## Miscellaneous small tasks (~1 week)

- [x] Add more to the explanation of environment variables (make sure to link to the [Twelve-Factor App docs](https://12factor.net/))
- [x] Add contributing guidelines
- [x] #172
- [x] #170
- [x] #167
- [x] #39
- [x] #73
- [x] #89
- [x] #95
- [x] #85
- [x] #91
- [x] #92
- [x] What is the model for an affiliation.
- [x] #84
- [x] #83
- [ ] #102

## Questions
- [x] #86
- [x] #87
- [x] #88
